stages:
- build
#- test
#- deploy

.build_container_function: &build_container_function |
  export CI_APPLICATION_REPOSITORY=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
  
  function show_usage() {
    echo "Todo"
    exit 1
  }

  function build_container() {
    set -x
    if [[ $# -ne 2 ]] ; then
      show_usage
    elif [[ "$1" == "docker" ]] ; then
      docker build $2
    elif [[ "$1" == "podman" ]] ; then
      echo "Todo"
    else
      show_usage
    fi
  }

  build_container docker .

build_container:
  stage: build
  before_script:
  - *build_container_function
  script:
  - echo "build_container executed!"
    #- build_container_function docker .


#Note: You can’t use YAML anchors across multiple files when leveraging the include feature. Anchors are only valid within the file they were defined in.