# This file is a template, and might need editing before it works on your project.
docker-build-master:
  # Official docker image.
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" .
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$CI_REGISTRY_IMAGE:latest"
    - docker logout
    - echo $DOCKER_HUB_PASSWD_B64 | base64 -d | docker login --password-stdin -u "$DOCKER_HUB_USER" $DOCKER_HUB_URL
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA teutonet/ci-tools:$CI_COMMIT_SHORT_SHA
    - docker push "teutonet/ci-tools:$CI_COMMIT_SHORT_SHA"
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA teutonet/ci-tools:latest
    - docker push "teutonet/ci-tools:latest"
  after_script:
    - docker logout
  only:
    - master

docker-build:
  # Official docker image.
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay

  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
