stages:
- build
#- test
#- deploy

.build_container_function: &build_container_function |
  export CI_APPLICATION_REPOSITORY=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
  
  function show_usage() {
    echo "Todo"
    exit 1
  }

  function build_container() {
    if [[ $# -ne 2 ]] ; then
      show_usage
    elif [[ "$1" == "docker" ]] ; then
      docker_build $1 $2
    elif [[ "$1" == "podman" ]] ; then
      echo "Todo"
    else
      show_usage
    fi
  }

  function docker_build() {
    docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" $2
    docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  }

  function podman_build() {
    echo "Nothing happening yet"
  }

  build_container docker .

build_container:
  image: registry-gitlab.teuto.net/kubernetes/generic-ci:latest
  stage: build
  before_script:
  - *build_container_function
  script:
  - echo "build_container executed!"
    #- build_container_function docker .


#Note: You can’t use YAML anchors across multiple files when leveraging the include feature. Anchors are only valid within the file they were defined in.